### ISSUE TITLE
[JOSS] Automated Tests

### ISSUE THREAD

**Issue by HaoZeke** [Muhao-Chen/Tensegrity_Finite_Element_Method_TsgFEM#1]
Part of https://github.com/openjournals/joss-reviews/issues/3390.

It is necessary to include [unit tests](https://www.mathworks.com/help/matlab/matlab-unit-test-framework.html) and instructions to run them; without which over time the maintainability of the software will suffer.

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by Muhao-Chen** [comment]
@HaoZeke Thanks for your comments! 
Please have a look at the  Tensegrity_Finite_Element_Method_TsgFEM/Software_Verification_and_Examples/Dynamics_Examples/03_double_pendulum/
Tensegrity_Finite_Element_Method_TsgFEM/Software_Verification_and_Examples/Dynamics_Examples/05_T_bar_Dynamics/
These simple examples are given as unit tests. For the double pendulum example, we also compare the results with rigid body dynamics. We also updated the comments in the codes and descriptions. Thank you!

**Comment by Muhao-Chen** [comment]
@HaoZeke @diehlpk Thanks for pointing it out. We also updated the 
Tensegrity_Finite_Element_Method_TsgFEM/User_Guide/User_Guide_Tensegrity_Finite_Element_Method_(TsgFEM) .pdf
As you may see, the unit tests examples, procedures, and results are described in detail in this pdf.  Thank you!

**Comment by diehlpk** [comment]
@HaoZeke Please have a look at the new changes.

**Comment by diehlpk** [comment]
@HaoZeke Please have a look at the new changes.

**Comment by HaoZeke** [comment]
This has been resolved.
