### ISSUE TITLE
[JOSS] Paper updates

### ISSUE THREAD

**Issue by HaoZeke** [Muhao-Chen/Tensegrity_Finite_Element_Method_TsgFEM#2]
Part of https://github.com/openjournals/joss-reviews/issues/3390.

The software paper should:
- include some of the algorithms and a clearer methodology section describing the software suite
- describe the structure and layout of the code
- provide a graphical overview of accuracy v.s. size
- describe the examples (since they are mentioned for the accuracy)
- describe the interface to ANSYS in more detail

**Comment by likask** [comment]
My suggestions in addition to @HaoZeke 

- Explain the name and purpose of the code in the first paragraph. Consider breaking summary—introduction with literature review and physical and numerical assumptions.
- Do not mix assumptions about the physical problem and numerical discretisation.
- Consider adding figures with results and deformation on the first page. That will give short insight into what your code does. 
-  Do not use "Accurate FEM dynamics". You have quasi rigid members for large stiffness and elastic or elasto-plastic membres.  FEM is discretisation method. 
- You can mention solution schemes, which you are using to solve the nonlinear problem, dynamic problem, or natural frequency problem.
- Using terms like "natural frequency errors are about 10−14" is imprecise; we do not know if this is absolute or relative error. I would suggest writing that both codes, Ansys and TsgFEM give errors which in numerical precision for some particular tested problems.

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by diehlpk** [comment]
@Muhao-Chen Could you please have a look here as well?

**Comment by Muhao-Chen** [comment]
@HaoZeke @likask @diehlpk Thank you so much for your helpful comments! We have updated the paper. 
https://github.com/Muhao-Chen/Tensegrity_Finite_Element_Method_TsgFEM/blob/main/JOSS_paper/paper.md
Plus, we also have an updated user manual. All the procedures are in detailed steps. We believe this user manual would help users get comfortable with the software. Thank you! 
https://github.com/Muhao-Chen/Tensegrity_Finite_Element_Method_TsgFEM/blob/main/User_Guide/User_Guide_Tensegrity_Finite_Element_Method_(TsgFEM)%20.pdf

**Comment by HaoZeke** [comment]
Thanks for addressing these points.
